/** 中文 => 英文字段映射 */
/** 成品 */
export const finishedHeaderMap: Record<string, string> = {
  '条码': 'code',
  '货品名称': 'name',
  '入网费': 'access_fee',
  '零售方式': 'retail_type',
  '标签价': 'label_price',
  '零售工费': 'labor_fee',
  '款号': 'style',
  '供应商': 'supplier',
  '品牌': 'brand',
  '大类': 'class',
  '材质(贵金属成分)': 'material',
  '成色': 'quality',
  '实际成色': 'quality_actual',
  '主石(宝玉石种类)': 'gem',
  '品类': 'category',
  '工艺': 'craft',
  '切工': 'cut',
  '金重(g)': 'weight_metal',
  '总重(g)': 'weight_total',
  '手寸': 'size',
  '贵金属颜色': 'color_metal',
  '主石重': 'weight_gem',
  '主石数量': 'num_gem',
  '副石1重': 'weight_other',
  '副石1数量': 'num_other',
  '颜色': 'color_gem',
  '净度': 'clarity',
  '系列': 'series',
  '备注': 'remark',
  '是否特价': 'is_special_offer',
}

/** 旧料 */
export const oldHeaderMap: Record<string, string> = {
  '旧料条码': 'code',
  '名称': 'name',
  '是否自有': 'is_our',
  '所属店铺': 'store',
  '回收类型': 'recycle_type',
  '回收来源': 'recycle_source',
  '回收门店': 'recycle_store',
  '回收方式': 'recycle_method',
  '回收金额': 'recycle_price',
  '回收金价': 'recycle_price_gold',
  '回收工费': 'recycle_price_labor',
  '回收工费方式': 'recycle_price_labor_method',
  '大类': 'class',
  '入网费': 'access_fee',
  '零售方式': 'retail_type',
  '标签价': 'label_price',
  '零售工费': 'labor_fee',
  '款号': 'style',
  '供应商': 'supplier',
  '品牌': 'brand',
  '材质(贵金属成分)': 'material',
  '成色': 'quality',
  '主石(宝玉石种类)': 'gem',
  '品类': 'category',
  '工艺': 'craft',
  '金重(g)': 'weight_metal',
  '总重(g)': 'weight_total',
  '手寸': 'size',
  '贵金属颜色': 'color_metal',
  '主石重': 'weight_gem',
  '主石数': 'num_gem',
  '副石重': 'weight_other',
  '副石数': 'num_other',
  '颜色': 'color_gem',
}

export const statementHeaderMap: Record<string, string> = {
  编号: 'id',
  关联销售单: 'order_id',
  订单状态: 'status',
  门店: 'store',
  产品条码: 'code',
  会员: 'member.name',
  会员手机号: 'member.phone',
  类型: 'type',
  订单来源: 'source',
}
