/** 中文 => 英文字段映射 */
/** 成品 */
export const finishedHeaderMap: Record<string, string> = {
  '门店': 'store',
  '条码': 'code',
  '货品名称': 'name',
  '入网费': 'access_fee',
  '零售方式': 'retail_type',
  '标签价': 'label_price',
  '零售工费': 'labor_fee',
  '款号': 'style',
  '供应商': 'supplier',
  '品牌': 'brand',
  '大类': 'class',
  '材质(贵金属成分)': 'material',
  '成色': 'quality',
  '实际成色': 'quality_actual',
  '主石(宝玉石种类)': 'gem',
  '品类': 'category',
  '工艺': 'craft',
  '切工': 'cut',
  '金重(g)': 'weight_metal',
  '总重(g)': 'weight_total',
  '手寸': 'size',
  '贵金属颜色': 'color_metal',
  '主石重': 'weight_gem',
  '主石数量': 'num_gem',
  '副石1重': 'weight_other',
  '副石1数量': 'num_other',
  '颜色': 'color_gem',
  '净度': 'clarity',
  '系列': 'series',
  '备注': 'remark',
  '是否特价': 'is_special_offer',
  '库龄': 'enter_time',
}

/** 旧料 */
export const oldHeaderMap: Record<string, string> = {
  '门店': 'store',
  '条码': 'code',
  '名称': 'name',
  '是否自有': 'is_our',
  '所属店铺': 'store',
  '回收类型': 'recycle_type',
  '回收来源': 'recycle_source',
  '回收门店': 'recycle_store',
  '回收方式': 'recycle_method',
  '回收金额': 'recycle_price',
  '回收金价': 'recycle_price_gold',
  '回收工费': 'recycle_price_labor',
  '回收工费方式': 'recycle_price_labor_method',
  '大类': 'class',
  '入网费': 'access_fee',
  '零售方式': 'retail_type',
  '标签价': 'label_price',
  '零售工费': 'labor_fee',
  '款号': 'style',
  '供应商': 'supplier',
  '品牌': 'brand',
  '材质(贵金属成分)': 'material',
  '成色': 'quality',
  '主石(宝玉石种类)': 'gem',
  '品类': 'category',
  '工艺': 'craft',
  '金重(g)': 'weight_metal',
  '总重(g)': 'weight_total',
  '手寸': 'size',
  '贵金属颜色': 'color_metal',
  '主石重': 'weight_gem',
  '主石数': 'num_gem',
  '副石重': 'weight_other',
  '副石数': 'num_other',
  '颜色': 'color_gem',
}

/** 旧料 */
export const oldUnclassHeaderMap: Record<string, string> = {
  '条码': 'code',
  '名称': 'name',
  '是否自有': 'is_our',
  '所属店铺': 'store',
  '回收类型': 'recycle_type',
  '回收来源': 'recycle_source',
  '回收门店': 'recycle_store',
  '回收方式': 'recycle_method',
  '回收金额': 'recycle_price',
  '回收金价': 'recycle_price_gold',
  '回收工费': 'recycle_price_labor',
  '回收工费方式': 'recycle_price_labor_method',
  '成品大类': 'finished_class',
  '旧料大类': 'old_class',
  '入网费': 'access_fee',
  '零售方式': 'retail_type',
  '标签价': 'label_price',
  '零售工费': 'labor_fee',
  '款号': 'style',
  '供应商': 'supplier',
  '品牌': 'brand',
  '材质(贵金属成分)': 'material',
  '成色': 'quality',
  '主石(宝玉石种类)': 'gem',
  '品类': 'category',
  '工艺': 'craft',
  '金重(g)': 'weight_metal',
  '总重(g)': 'weight_total',
  '手寸': 'size',
  '贵金属颜色': 'color_metal',
  '主石重': 'weight_gem',
  '主石数': 'num_gem',
  '副石重': 'weight_other',
  '副石数': 'num_other',
  '颜色': 'color_gem',
}

export const statementHeaderMap: Record<string, string> = {
  '门店': 'store',
  '关联销售单': 'order_id',
  '本单实收': 'price_pay',
  '定金抵扣': 'price_deposit',
  '订单状态': 'status',
  '订单来源': 'source',
  '主销': 'mainSale',
  '会员': 'member_name',
  '会员手机号': 'member_phone',
  '会员折扣': 'discount_member',
  '类型': 'type',
  '货品名称': 'name',
  '成品条码': 'code',
  '旧料编号': 'code_old',
  '大类': 'class',
  '商品原价': 'price_original',
  '应付金额': 'amount_price',
  '标签价': 'label_price',
  '折扣': 'discount_final',
  '成品金价': 'product_price_gold',
  '成品工费': 'labor_fee_product',
  '零售方式': 'retail_type',
  '旧料抵扣': 'price_old',
  '回收方式': 'recycle_method',
  '回收金价': 'recycle_price_gold',
  '回收工费': 'recycle_price_labor',
  '回收金重': 'recycle_weight_metal',
  '回收工费方式': 'recycle_price_labor_method',
  '回收积分': 'recycle_points',
  '实际成色': 'quality_actual',
  '配件单价': 'accessory_price',
  '配件零售方式': 'accessory_retail_type',
  '配件数量': 'accessory_quantity',
  '配件类型': 'accessory_type',
  '供应商': 'supplier',
  '品牌': 'brand',
  '材质': 'material',
  '成色': 'quality',
  '主石': 'gem',
  '品类': 'category',
  '工艺': 'craft',
  '金重(g)': 'weight_metal',
  '总重(g)': 'weight_total',
  '备注': 'remark',
}

export const checkHeaderMap: Record<string, string> = {
  调出门店: 'from_store_id',
  调入门店: 'to_store_id',
  调入区域: 'to_region_id',
  调拨单号: 'id',
  发起人: 'initiator_id',
  接收人: 'receiver_id',
  调拨单状态: 'status',
  调拨类型: 'method',
  仓库类型: 'type',
  调拨原因: 'reason',
  调拨数量: 'product_count',
  调拨金重: 'product_total_weight_metal',
  调拨标签价: 'product_total_label_price',
  调拨备注: 'remark',
  开始时间: 'created_at',
  完成时间: 'updated_at',
}

export const checkHeaderMapA: Record<string, string> = {
  调出门店: 'from_store_id',
  调入门店: 'to_store_id',
  调拨单号: 'id',
  发起人: 'initiator_id',
  接收人: 'receiver_id',
  调拨单状态: 'status',
  调拨类型: 'method',
  仓库类型: 'type',
  调拨原因: 'reason',
  调拨备注: 'remark',
  开始时间: 'created_at',
  完成时间: 'updated_at',
}

export const accessorieHeaderMap: Record<string, string> = {
  编号: 'code',
  名称: 'name',
  库存: 'stock',
  类型: 'type',
  零售方式: 'retail_type',
  单价: 'price',
}
